[package]
name = "datetime_literal"
version = "0.1.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/avl/datetime_literal"
description = "A macro for creating chrono::DateTime instances."
keywords = ["literal", "datetime", "macro"]

[dependencies]
chrono="0.4.39"
